### ISSUE TITLE
warning:unknown prop errors

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-react-sample#13]
There is a lot of this errors in 00, 01, 02, 03 projects
![screenshot_3](https://cloud.githubusercontent.com/assets/1114365/16818756/0f1a60de-4952-11e6-9c98-b7d0809c0dd6.png)

**Comment by ericelliott** [comment]
These are only warnings. Everything should work fine. This should be fixed in `react-bootstrap` rather than here. You can track progress in [this issue](https://github.com/react-bootstrap/react-bootstrap/issues/1994).

**Comment by chenkie** [comment]
Fixed with latest react and react-bootstrap
