### ISSUE TITLE
Unnecessary `offsetSeconds`

### ISSUE THREAD

**Issue by jiahaog** [auth0-samples/auth0-react-sample#18]
I'm not really sure if I'm missing something, but it appears that `offsetSeconds` does nothing here:

https://github.com/auth0-samples/auth0-react-sample/blob/master/10-Customizing-Lock/src/utils/jwtHelper.js#L16

```
export function isTokenExpired(token){
  const date = getTokenExpirationDate(token)
  const offsetSeconds = 0
  if (date === null) {
    return false
  }
  return !(date.valueOf() > (new Date().valueOf() + (offsetSeconds * 1000)))
}
```

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
