### ISSUE TITLE
How to run app?

### ISSUE THREAD

**Issue by scheung38** [auth0-samples/auth0-react-sample#23]
There is no package.json in root?

But after npm init

$ npm install

$ npm start

nothing happens...

**Comment by chenkie** [comment]
Are you doing this in the root folder or in one of the sub folders? It should be done from the individual sub folders :)

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
