### ISSUE TITLE
Not Able to redirect to home page after login

### ISSUE THREAD

**Issue by anshul-shukla** [auth0-samples/auth0-react-sample#25]
I am using - https://auth0.com/docs/quickstart/spa/react/01-login approach for login on my app. Everything is working fine except after login it is not redirecting to `home` page. 

After redirection url i am getting - `/login#`

Here is my route - 

```
<Router history={browserHistory}>
    <Route path="/" component={App} auth={auth}>
      <IndexRedirect to="/home" />
      <Route path="/login" component={Login}/>
      <Route path="/home" component={AppComponent} onEnter={requireAuth}>
        <Route path="/match" component={Match}/>
        <Route path="/player" component={Player}/>
      </Route>
    </Route>
  </Router>
```

Any Clue ?

**Comment by juanpicado** [comment]
The access token is missing in your Router children
` <Route path="access_token=:token" component={Login} />`
I'm facing problems using `browserHistory` instead the `hashHistory`.  I could not fix it yet.

**Comment by jeveloper** [comment]
@juanpicado same here with a fairly basic app, browserHistory doesnt seem to work.

Strange that tutorial uses browserhistory, github is different

**Comment by frankcalise** [comment]
I'm also experiencing this, has anyone come up with a solution? About to contact auth0 support to see if they have any idea.

**Comment by jeveloper** [comment]
Reverted back to using hashHistory and url path

**Comment by danielstecki** [comment]
I ended up getting around this by setting redirect false in the lock settings and then handling the redirect in the setToken callback using browserHistory.push().

export default class AuthService extends EventEmitter {
  constructor(clientId, domain) {
    super()
    // Configure Auth0
    this.lock = new Auth0Lock(clientId, domain, {
      auth: {
        redirect: false
      },
      autoclose: true,
....
setToken(idToken){
    // Saves user token to localStorage
    localStorage.setItem('id_token', idToken)
    browserHistory.push('/admin')
  }

Make sure you have autoclose set to true so that the auth window doesn't stay open.

**Comment by twgraham** [comment]
Ive been bitten in the past by this issue, however i was kind of rolling my own webpack config using webpack-dev-server over hjs-server. Curious, is anyone doing the same, or are people having issues with browser history with the default repo setup?

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
