### ISSUE TITLE
Cannot reach the server

### ISSUE THREAD

**Issue by dungkhuc** [auth0-samples/auth0-react-sample#27]
Hi,
I'm trying to get the first example 01-login to work. 

When I attempt to login, the app shows this message:

`WE COULD NOT REACH THE SERVER. PLEASE CHECK YOUR CONNECTION AND TRY AGAIN.`

I haven't made any change to the app except putting auth0 client details into `.env`. I'm using europe domain: `eu.auth0.com`.

**Comment by dungkhuc** [comment]
I had to add `http://localhost` to `Allowed Callback URLs` in auth0 client settings. It could have been nice if this were mentioned in the tutorial.

**Comment by tverilytt** [comment]
@dungkhuc Do you have a sample of adding that setting?

**Comment by sean-perryman** [comment]
https://imgur.com/a/LE2Aq

This is how I interpreted the setting to be input, but I was (as of yet) unable to get this working.
