### ISSUE TITLE
I can't get the login screen to show.

### ISSUE THREAD

**Issue by walterbelleville** [auth0-samples/auth0-react-sample#28]
I can't get the login screen to show from the sample code.  I have tried 01-Login and 10-Customizing-lock, and I get the no login screen.  What am I missing?

**Comment by chenkie** [comment]
Are you getting any errors in the console?

**Comment by walterbelleville** [comment]
Yes, I am getting two errors.

GET https://%7Bratethisrecipe.auth0.com%7D/client/%7BTSXTLh6qwQ4QGSHGkQ6T0VEFZ0pAey5L%7D.js?t1478481535388 net::ERR_NAME_NOT_RESOLVEDload 

Uncaught Error: Error: An error ocurred when fetching data.
    at eval (eval at <anonymous> (http://localhost:3000/app.js:3448:2), <anonymous>:538:13)

**Comment by chenkie** [comment]
It looks like you've got brackets around your Auth0 credentials but it should just be quotes :) Like this in your `.env`:

```bash
AUTH0_CLIENT_ID='TSXTLh6qwQ4QGSHGkQ6T0VEFZ0pAey5L'
AUTH0_DOMAIN='ratethisrecipe.auth0.com'
```

**Comment by walterbelleville** [comment]
That was the problem.  Thanks.
