### ISSUE TITLE
Prerendered HTML files

### ISSUE THREAD

**Issue by miksansegundo** [auth0-samples/auth0-react-sample#31]
Hi, thanks for these great examples!

With the actual configuration of this nice hjs-webpack that uses CSS modules and path aliases like "utils" I'm not able to use the html function to prerender specific files. 

Do you have any example or experience on that? Would be a nice improvement to prevent FOUC.

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
