### ISSUE TITLE
bootstrap/dist/css/bootstrap.css doesn't exist

### ISSUE THREAD

**Issue by jakehm** [auth0-samples/auth0-react-sample#33]
In the latest version of react-bootstrap, it doesn't exist at least.  You have to link to the cdn I think.
 Example one is trying to import it:
import 'bootstrap/dist/css/bootstrap.css'

[https://github.com/auth0-samples/auth0-react-sample/blob/master/01-Login/src/app.js](url)

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
