### ISSUE TITLE
Token validation is failing

### ISSUE THREAD

**Issue by saidkholov** [auth0-samples/auth0-react-sample#34]
First thing I wanted to point out is that there is mismatch in documentation and the actual code:
in `auth0-react-sample/08-Calling-Api/server.js`
```
var authenticate = jwt({
  secret: new Buffer(process.env.AUTH0_SECRET, 'base64'),
  audience: process.env.AUTH0_CLIENT_ID
});
```
In the actual documentation the example doesn't use `new Buffer`

Secondly, both solutions did not work for my applications and after hours of research I found that this code works:

```
app.use(jwt({
  // Dynamically provide a signing key based on the kid in the header and the singing keys provided by the JWKS endpoint
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://{YOUR_AUTH0_DOMAIN}/.well-known/jwks.json`
  }),


  // Validate the audience and the issuer
  audience: '{YOUR_API_IDENTIFIER}',
  issuer: 'https://{YOUR_AUTH0_DOMAIN}/',
  algorithms: [ 'RS256' ]
}));
```

Found on:
[https://auth0.com/docs/architecture-scenarios/application/server-api/api-implementation-nodejs](https://auth0.com/docs/architecture-scenarios/application/server-api/api-implementation-nodejs)

Is it just me who has this problem or the documentations needs an update?

**Comment by chenkie** [comment]
Thanks @saidkholov. We recently made a change where we're no longer Base64 encoding client secrets. I've changed over the server example in this repo to reflect that.

It looks like you're using the new API authorization features from Auth0. Revamped documentation to show this usage is underway.

**Comment by saidkholov** [comment]
Great,👍👍. I suppose you can close the issue once the docs are updated

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
