### ISSUE TITLE
Does 02-Custom-Login app work with Custom Database?

### ISSUE THREAD

**Issue by cwoodruff** [auth0-samples/auth0-react-sample#35]
I cannot get the app to work and always get a 404 error from the Auth0 API. Seems like a simple React app. Anyone using a Custom Database give me clues into getting the code to work? Thanks

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
