### ISSUE TITLE
LocalStorage in a Node-React app

### ISSUE THREAD

**Issue by JohnnyBizzel** [auth0-samples/auth0-react-sample#37]
I've no idea how to implement LocalStorage in React yet so I tried installing node-localstorage which lead to this error:
```
  var fs$ReadStream = fs.ReadStream
  ReadStream.prototype = Object.create(fs$ReadStream.prototype) // throws error...
```
Uncaught TypeError: Cannot read property 'prototype' of undefined

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
