### ISSUE TITLE
Options not being passed to lock through AuthService

### ISSUE THREAD

**Issue by davidweisss** [auth0-samples/auth0-react-sample#38]
Since this is set as Auth0Lock 'options' inside AuthService
 { 
          auth:
          { 
            redirectUrl: `${window.location.origin}/login`,
            responseType: 'token'
          }
        }

options provided to AuthService get ignored...

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)
