### ISSUE TITLE
02-custom login google-oauth2

### ISSUE THREAD

**Issue by Sashkan** [auth0-samples/auth0-react-sample#46]
I don't get it, isn't this supposed to log me in ? When using the username-password method, I get redirected to /home, when using the google-oauth2 method, nothing happens, except a 
```
[HMR] connected
```
in console. 

EDIT: It seems to come from react-router ```onEnter``` method in routes.js, which doesn't trigger.

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :)

Check whether the router issues you were getting here still show up with the latest samples.
