### ISSUE TITLE
Following the tutorial requires react-router@^3.x.x, not @^4.x.x

### ISSUE THREAD

**Issue by Sugarcaen** [auth0-samples/auth0-react-sample#49]
Following the documentation from [Auth0 React SDK Quickstarts](https://auth0.com/docs/quickstart/spa/react/00-getting-started) the initial application will fail because react-router changes the way history is created in 4.x.x

Changing the package.json required version to ^3.x.x allows the quickstarts to be followed.

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :) These new ones use router v4.
