### ISSUE TITLE
Update guides to react router 4

### ISSUE THREAD

**Issue by juliankmazo** [auth0-samples/auth0-react-sample#50]
I've been founding some issues following the guides and is because they're outdated. You guys are thinking in updating the code to use it with react router 4?
For example like the `onEnter` callback that is not available anymore https://github.com/auth0-samples/auth0-react-sample/blob/master/02-Custom-Login/src/views/Main/routes.js
https://github.com/ReactTraining/react-router/issues/4976

**Comment by stevebingsoo** [comment]
Yes please update your guide.  I'm having a frustrating time

**Comment by colemannerd** [comment]
I am as well.  React Router 4 is really different and it is a bit overwhelming to try and figure out auth0 and react router 4 at the same time.

**Comment by Gdewilde** [comment]
Please update this, thanks.

**Comment by kempsterrrr** [comment]
Upvote 👍

**Comment by dcorb** [comment]
👍

**Comment by dcorb** [comment]
I'm testing with these samples  https://github.com/auth0-samples/auth0-react-samples/tree/4b4d683c2ac4f557a8fb4b3099488d1fd0651f78

**Comment by chenkie** [comment]
Closing this out as the samples have been deprecated in favor the [latest ones](https://github.com/auth0-samples/auth0-react-samples) :) These samples use router v4

**Comment by aricma** [comment]
hi, I just took a look at these examples and they are working but they are not using HashHistory. Is there a way to use ReactRouter 4 with HashHistory and Auth0 ?
